apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 8
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: r0h17h/consumer:latest
          envFrom:
            - configMapRef: 
                name: consumer-configmap
            - secretRef:
                name: consumer-secret
