DROP USER IF EXISTS 'auth_user'@'%';

CREATE USER 'auth_user' IDENTIFIED BY 'auth123';
CREATE DATABASE IF NOT EXISTS auth;

GRANT ALL PRIVILEGES ON auth.* TO 'auth_user';
FLUSH PRIVILEGES;

USE auth;

CREATE TABLE IF NOT EXISTS User(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

INSERT INTO User (email, password) VALUES ('rohithvarmadatla15@gmail.com', 'Rohith1234');
